namespace: production

resources:
  - ../../base

replicas:
  - name: backend
    count: 3

  - name: frontend
    count: 3

configMapGenerator:
  - name: app-config
    literals:
      - ENV=production

secretGenerator:
  - name: app-secret
    literals:
      - DB_PASSWORD=productionpassword
